DEBUG=0
FINALPACKAGE=1
GO_EASY_ON_ME=1
ARCHS = arm64

THEOS_PACKAGE_SCHEME = rootless

include $(THEOS)/makefiles/common.mk

TOOL_NAME = edictusroot

edictusroot_FILES = main.m
edictusroot_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tool.mk
